from __future__ import annotations

from os import PathLike
from pathlib import Path


def _format_value(value) -> str:
    """
    INTENDED FOR INTERNAL USE ONLY

    Render a single Python value the way the parser expects to read it back: None becomes `null` and bools become
    `true`/`false`. Everything else is rendered with `str`.
    """
    if value is None:
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    return str(value)


def generate_config(conf_obj: dict, indent: str = '\t') -> str:
    """
    Generate and return a valid config from an object.
    Will save the config if an output file is passed.

    This WILL NOT currently write valid .ini files, so don't even try. The only output format is secsie.

    Empty string values are written as commented out lines (at the top level and in sections), so they are not
    present when the generated config is parsed again.

    :param conf_obj: The dictionary to parse into a configuration language string
    :param indent: The character(s) to use for indentation. Can be tab or spaces. Defaults to tab character, '\t'
    :return: a string of configuration code
    :raises TypeError: if a section contains a dict, since secsie does not support nested dicts
    """

    conf = ''
    for key, value in conf_obj.items():
        if isinstance(value, dict):
            conf += f"\n[{key.replace(' ', '')}]\n"
            for k, v in value.items():
                if isinstance(v, dict):
                    raise TypeError(
                        f"Cannot generate config: '{key}.{k}' is a dict, but nested dicts are not supported. "
                        f"Secsie only has one level of sections, so a section's values must be strings, numbers, "
                        f"booleans, None, or lists."
                    )
                elif isinstance(v, list):
                    conf += f'\t{k} = {", ".join(_format_value(i) for i in v)}\n'
                else:
                    conf += f"{';' if v == '' else ''}{indent}{k} = {_format_value(v)}\n"
            conf += "\n"
            continue
        elif isinstance(value, list):
            conf += f'{key} = {", ".join(_format_value(i) for i in value)}\n'
            continue
        conf += f"{';' if value == '' else ''}{key} = {_format_value(value)}\n"

    return conf


def generate_config_file(conf_obj: dict, output_file: str | PathLike[str], indent: str = '\t'):
    """
    Generate and write a config file from a dictionary of keys and values

    :param conf_obj: The dictionary to render into the secsie config language
    :param output_file: The file to write to
    :param indent: The character(s) to use for indentation. Can be tab or spaces. Defaults to tab character, '\t'
    """
    output_file = Path(output_file)
    conf = generate_config(conf_obj, indent=indent)

    with open(output_file, 'w') as f:
        f.write(f"# {output_file.name} auto-generated by secsie\n{conf}")
