name: Deploy to PyPi on Release

on:
  release:
    types: [published]


jobs:
  deploy:
    name: Deploy Package to PyPi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install twine and wheel
        run: python -m pip install twine wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
