name: Deploy to PyPi on Release

on:
  release:
    types: [published]


jobs:
  deploy:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install twine
        run: python -m pip install twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload dist/*
